<?php

use Sifo\Bootstrap;
use Sifo\Cache;
use Sifo\Cache\Disk;

/**
 * Test class for Cache.
 * Generated by PHPUnit on 2009-11-01 at 12:17:06.
 */
class CacheTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Cache
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        Bootstrap::$instance = 'tests';
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->object = null;
    }

    /** @test */
    public function should_return_disk_cache()
    {
        $this->object = Cache::getInstance(Cache::CACHE_TYPE_DISK);
        $this->assertTrue($this->object instanceof Disk);
    }
}


