<?php

CoverageAnalysis::add( ROOT_PATH . '/libs/Sifo/Config.php' );

/**
 * Yea, a mock to override the constructor, truly great.
 */
class ConfigMock extends \Sifo\Config
{
	public function __construct( $instance_name )
	{
		return parent::__construct( $instance_name );
	}
}

/**
 * Test class for Config.
 * Generated by PHPUnit on 2009-11-01 at 12:17:05.
 */
class ConfigTest extends PHPUnit_Extensions_ControllerTest
{
    /**
     * @var Config
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
	    $this->object = new ConfigMock( 'tests' );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
	    $this->object = null;
    }

	/**
	 * Test object correct creation.
	 */
	public function testObjectCreation()
	{
		$this->assertTrue( $this->object instanceof \Sifo\Config );
	}
}
?>
