<?php
ini_set("include_path", "../libs/Sifo".PATH_SEPARATOR."../../../libs/Sifo".PATH_SEPARATOR.ini_get("include_path"));
require_once 'PHPUnit/Framework.php';

require_once '/var/www/seoframework/libs/Sifo/Dir.php';

/**
 * Test class for Dir.
 * Generated by PHPUnit on 2009-11-01 at 12:17:04.
 */
class DirTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Dir
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Dir;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetFileListRecursive().
     */
    public function testGetFileListRecursive()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetDirs().
     */
    public function testGetDirs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
