<?php

use Sifo\Exception\SEO\Exception303;

/**
 * Test class for Exception303.
 * Generated by PHPUnit on 2009-11-01 at 12:17:01.
 */
class Exception303Test extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Exception303
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Exception303;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}

