<?php

use Sifo\Exception\SEO\Exception401;

/**
 * Test class for Exception401.
 * Generated by PHPUnit on 2009-11-01 at 12:17:00.
 */
class Exception401Test extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Exception401
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Exception401;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}

