<?php

use Sifo\Exception\SEO\Exception403;

/**
 * Test class for Exception403.
 * Generated by PHPUnit on 2009-11-01 at 12:17:02.
 */
class Exception403Test extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Exception403
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Exception403;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}

