<?php
ini_set("include_path", "../libs/Sifo".PATH_SEPARATOR."../../../libs/Sifo".PATH_SEPARATOR.ini_get("include_path"));
require_once 'PHPUnit/Framework.php';

require_once '/var/www/seoframework/libs/Sifo/Mail.php';

/**
 * Test class for Mail.
 * Generated by PHPUnit on 2009-11-01 at 12:16:59.
 */
class MailTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Mail
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Mail;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testSend().
     */
    public function testSend()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
