<?php

/**
 * Test class for Redis_Exception.
 * Generated by PHPUnit on 2009-11-01 at 12:16:56.
 */
class Redis_ExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Redis_Exception
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Redis_Exception;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}

