<?php

$config['ads/google.tpl'] = 'vendor/sifophp/sifo/templates/ads/google.tpl';
$config['debug/analyzer.tpl'] = 'vendor/sifophp/sifo/templates/debug/analyzer.tpl';
$config['debug/analyzer_modules/basic_debug.tpl'] = 'vendor/sifophp/sifo/templates/debug/analyzer_modules/basic_debug.tpl';
$config['debug/analyzer_modules/cookies.tpl'] = 'vendor/sifophp/sifo/templates/debug/analyzer_modules/cookies.tpl';
$config['debug/analyzer_modules/database.tpl'] = 'vendor/sifophp/sifo/templates/debug/analyzer_modules/database.tpl';
$config['debug/analyzer_modules/headers.tpl'] = 'vendor/sifophp/sifo/templates/debug/analyzer_modules/headers.tpl';
$config['debug/analyzer_modules/log_messages.tpl'] = 'vendor/sifophp/sifo/templates/debug/analyzer_modules/log_messages.tpl';
$config['debug/analyzer_modules/post.tpl'] = 'vendor/sifophp/sifo/templates/debug/analyzer_modules/post.tpl';
$config['debug/analyzer_modules/redis.tpl'] = 'vendor/sifophp/sifo/templates/debug/analyzer_modules/redis.tpl';
$config['debug/analyzer_modules/search.tpl'] = 'vendor/sifophp/sifo/templates/debug/analyzer_modules/search.tpl';
$config['debug/analyzer_modules/session.tpl'] = 'vendor/sifophp/sifo/templates/debug/analyzer_modules/session.tpl';
$config['debug/analyzer_modules/smarty_errors.tpl'] = 'vendor/sifophp/sifo/templates/debug/analyzer_modules/smarty_errors.tpl';
$config['debug/analyzer_modules/sphinxql.tpl'] = 'vendor/sifophp/sifo/templates/debug/analyzer_modules/sphinxql.tpl';
$config['debug/analyzer_modules/traces.tpl'] = 'vendor/sifophp/sifo/templates/debug/analyzer_modules/traces.tpl';
$config['debug/mail.tpl'] = 'vendor/sifophp/sifo/templates/debug/mail.tpl';
$config['debug/mini_debug.tpl'] = 'vendor/sifophp/sifo/templates/debug/mini_debug.tpl';
$config['empty.tpl'] = 'vendor/sifophp/sifo/templates/empty.tpl';
$config['error/30x_redirect.tpl'] = 'vendor/sifophp/sifo/templates/error/30x_redirect.tpl';
$config['error/404.tpl'] = 'vendor/sifophp/sifo/templates/error/404.tpl';
$config['error/40x.tpl'] = 'vendor/sifophp/sifo/templates/error/40x.tpl';
$config['error/500.tpl'] = 'vendor/sifophp/sifo/templates/error/500.tpl';
$config['error/common.tpl'] = 'vendor/sifophp/sifo/templates/error/common.tpl';
$config['home/index.tpl'] = 'vendor/sifophp/sifo/templates/home/index.tpl';
$config['home/pagination.tpl'] = 'vendor/sifophp/sifo/templates/home/pagination.tpl';
$config['i18n/status.tpl'] = 'vendor/sifophp/sifo/templates/i18n/status.tpl';
$config['locales/index.tpl'] = 'vendor/sifophp/sifo/templates/locales/index.tpl';
$config['manager/findi18n.tpl'] = 'vendor/sifophp/sifo/templates/manager/findi18n.tpl';
$config['manager/rebuild.tpl'] = 'vendor/sifophp/sifo/templates/manager/rebuild.tpl';
$config['manager/templates.tpl'] = 'vendor/sifophp/sifo/templates/manager/templates.tpl';
$config['manager/tpl_launcher.tpl'] = 'vendor/sifophp/sifo/templates/manager/tpl_launcher.tpl';
$config['shared/footer.tpl'] = 'vendor/sifophp/sifo/templates/shared/footer.tpl';
$config['shared/head.tpl'] = 'vendor/sifophp/sifo/templates/shared/head.tpl';
$config['shared/header.tpl'] = 'vendor/sifophp/sifo/templates/shared/header.tpl';
$config['shared/media_generator.tpl'] = 'vendor/sifophp/sifo/templates/shared/media_generator.tpl';
$config['shared/media_packer.tpl'] = 'vendor/sifophp/sifo/templates/shared/media_packer.tpl';
$config['shared/system_messages.tpl'] = 'vendor/sifophp/sifo/templates/shared/system_messages.tpl';
$config['static/common.tpl'] = 'vendor/sifophp/sifo/templates/static/common.tpl';
$config['user/login.tpl'] = 'vendor/sifophp/sifo/templates/user/login.tpl';

return $config;
