<?php
$config = array (
  'ads/google.tpl' => 'instances/common/templates/ads/google.tpl',
  'debug.tpl' => 'instances/common/templates/debug.tpl',
  'debug/mail.tpl' => 'instances/common/templates/debug/mail.tpl',
  'empty.tpl' => 'instances/common/templates/empty.tpl',
  'error/30x_redirect.tpl' => 'instances/common/templates/error/30x_redirect.tpl',
  'error/404.tpl' => 'instances/common/templates/error/404.tpl',
  'error/40x.tpl' => 'instances/common/templates/error/40x.tpl',
  'error/500.tpl' => 'instances/common/templates/error/500.tpl',
  'error/common.tpl' => 'instances/common/templates/error/common.tpl',
  'home/index.tpl' => 'instances/common/templates/home/index.tpl',
  'home/pagination.tpl' => 'instances/common/templates/home/pagination.tpl',
  'i18n/status.tpl' => 'instances/common/templates/i18n/status.tpl',
  'locales/index.tpl' => 'instances/common/templates/locales/index.tpl',
  'manager/findi18n.tpl' => 'instances/common/templates/manager/findi18n.tpl',
  'manager/templates.tpl' => 'instances/common/templates/manager/templates.tpl',
  'manager/tpl_launcher.tpl' => 'instances/common/templates/manager/tpl_launcher.tpl',
  'shared/footer.tpl' => 'instances/common/templates/shared/footer.tpl',
  'shared/head.tpl' => 'instances/common/templates/shared/head.tpl',
  'shared/header.tpl' => 'instances/common/templates/shared/header.tpl',
  'shared/media_generator.tpl' => 'instances/common/templates/shared/media_generator.tpl',
  'shared/media_packer.tpl' => 'instances/common/templates/shared/media_packer.tpl',
  'shared/system_messages.tpl' => 'instances/common/templates/shared/system_messages.tpl',
  'static/common.tpl' => 'instances/common/templates/static/common.tpl',
  'user/login.tpl' => 'instances/common/templates/user/login.tpl',
);