<?php
use Sifo\Cache\Disk;

/**
 * Test class for CacheDisk.
 * Generated by PHPUnit on 2009-11-01 at 12:17:06.
 */
class DiskTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Disk
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Disk;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->object = null;
    }

    /**
     * Test object correct creation.
     */
    public function testObjectCreation()
    {
        $this->assertInstanceOf(Disk::class, $this->object);
    }

}

